#version: '3.8'
#
#services:
#  app:
#    build: .
#    container_name: migraciones_poc
#    restart: always
#    ports:
#      - "8081:8081"

#version: '3.8'
#
#services:
#  jenkins:
#    image: jenkins/jenkins:lts
#    ports:
#      - "8080:8080"
#      - "50000:50000"
#    volumes:
#      - jenkins_home:/var/jenkins_home
#    restart: always
#
#volumes:
#  jenkins_home:

version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - app_network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: migraciones_poc
#    ports:
#      - "8081:8081"
#    networks:
#      - app_network
#    depends_on:
#      - jenkins

volumes:
  jenkins_home:

networks:
  app_network:

